### PR TITLE
Create 404 page

### PR DESCRIPTION
**Pull request by cloudyyoung**
It's just for now... Design better one later!

### CODE REVIEW

**Comment by tim-macphail** [comment]
404 page looks good, but I don't believe this will fix the routing behaviour I'm referring to. For example, just click this link https://lifeline.techstartucalgary.com/app/ and you'll get a 404.

**Comment by cloudyyoung** [comment]
> 

I mean cus this PR hasn't merged yet, so it's not on production yet and apparently that link will still give 404...

In my local environment it's working good, you should swicth to the branch and test locally.

**Comment by tim-macphail** [comment]
> > 
> 
> I mean cus this PR hasn't merged yet, so it's not on production yet and apparently that link will still give 404...
> 
> In my local environment it's working good, you should swicth to the branch and test locally.

Going directly to http://localhost:3000/app work on main and this branch, but not in build (and consequently production). 

On this branch when built, the only way to get this 404 page is to go to localhost/index.html ironically.

**Comment by cloudyyoung** [comment]
> > > 
> > 
> > 
> > I mean cus this PR hasn't merged yet, so it's not on production yet and apparently that link will still give 404...
> > In my local environment it's working good, you should swicth to the branch and test locally.
> 
> Going directly to http://localhost:3000/app work on main and this branch, but not in build (and consequently production).
> 
> On this branch when built, the only way to get this 404 page is to go to localhost/index.html ironically.

Not sure how it doesn't work for you. On my laptop I'm running the `vite preview` command and it works perfectly, and this approach worked for my previous projects.

https://user-images.githubusercontent.com/20573623/218286731-6c60eab7-d69a-4302-8e37-7d05f5479ddc.mov

If you have to access a page from `index.html` then that means your env is not routing _all_ urls to the app and that's not expected.

**Comment by tim-macphail** [comment]
Okay, we'll just try it and if it doesn't work we'll fix it

**Review by tim-macphail — APPROVED** [review]

**Comment by cloudyyoung** [comment]
😂 Github pages simply is not routing urls to react app, if you type in any route, eg https://lifeline.techstartucalgary.com/app, it'll always be 404.

**Comment by tim-macphail** [comment]
Yep... This is what I was trying to explain

**Comment by cloudyyoung** [comment]
Oh this PR provides a solution to display our customized 404 page when a page is not found and all urls are properly routed to react app as a pre-condition, otherwise even if all urls are routed properly, it's still gonna show Github pages 404 page.

Regarding the routing issue it's likely caused by vite migratio, similar to this [PR](https://github.com/vitejs/vite/issues/10925), so... it's out of the scope of PR, open a new one! 🤣

**Pull request merged**
