### PR TITLE
FE Refinement (1 / ∞): Improve DOM structure

### PR DESCRIPTION
**Pull request by cloudyyoung**
Some of the styles are not useful and introduces complexity for further changes, now they're removed and things are simplified.

This PR discards #99 and re-introduces #97, because `NavigationDrawer` **needs** to be `fixed`.

Didn't notice this, it's ugly... 😬
https://github.com/techstartucalgary/lifeline/blob/55db4bbf01ae31aae0ba3f9a6b185fb945ad4857/client/src/pages/Review/Review.tsx#L79

### CODE REVIEW

**Comment by tim-macphail** [comment]
I understand the removing of unnecessary styles, but I don't see what is the problem that the changes in `Review.tsx` fixes

**Comment by cloudyyoung** [comment]
> I understand the removing of unnecessary styles, but I don't see what is the problem that the changes in `Review.tsx` fixes

`NavigationDrawer` needs to be `fixed` so that it is **out of** flow layout and container style won't apply to it.

**Comment by cloudyyoung** [comment]
I'm having difficulty resolving conflict in this PR with #155

**Comment by tim-macphail** [comment]
> > I understand the removing of unnecessary styles, but I don't see what is the problem that the changes in `Review.tsx` fixes
> 
> `NavigationDrawer` needs to be `fixed` so that it is **out of** flow layout and container style won't apply to it.
> 
> See some css stuff: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flow_Layout/In_Flow_and_Out_of_Flow

I see that it makes logical sense to have the nav drawer out of flow, and maybe it takes a couple more lines of CSS to override the container styles. But I have a hard time changing something that's simple and works to something that's complicated and I don't know if it works. However, if you still want to follow through with this change I will go along with it, after extensive testing.

**Comment by cloudyyoung** [comment]
> > > I understand the removing of unnecessary styles, but I don't see what is the problem that the changes in `Review.tsx` fixes
> > 
> > 
> > `NavigationDrawer` needs to be `fixed` so that it is **out of** flow layout and container style won't apply to it.
> > See some css stuff: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flow_Layout/In_Flow_and_Out_of_Flow
> 
> I see that it makes logical sense to have the nav drawer out of flow, and maybe it takes a couple more lines of CSS to override the container styles. But I have a hard time changing something that's simple and works to something that's complicated and I don't know if it works. However, if you still want to follow through with this change I will go along with it, after extensive testing.

Thought I should probably follow up with some justifications.

Currently in main branch, the navbar is not fixed and as a part of the layout, it scrolls along with other content.

https://user-images.githubusercontent.com/20573623/220217803-e5845f4c-841e-4c15-a4f1-582ae6e16119.mov

However by the definition of a navbar, it shouldn't move as scrolling content. Here's an example of Youtube navbar:


https://user-images.githubusercontent.com/20573623/220218193-98f79aa4-3e35-4629-bf6b-1036e60889ea.mov

<br />


Making navbar **`fixed`** is making not only logical sense but also **visual sense**. And making an element `fixed` is the only way to make element floating above or below other contents, relative to the whole window (which is different from  what `absolute` provides: relative to a `relative` parent element).

Then making an element `fixed` is taking the element out of the layout flow, which is fairly explained in [that link](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flow_Layout/In_Flow_and_Out_of_Flow). 

The following two code snippets have no difference in effect:
```html
<body>
   <div class="parent">
     <div class="parent2">
      <div class="fixed"></div>
     </div>
   </div>
</body>
```
```html
<body>
   <div class="parent">
     <div class="parent2">
     </div>
   </div>
   <div class="fixed"></div>
</body>
```
Regardless of where you put fixed elements, everything in the layout flow won't observe them or effect them in styles by any means.  

So even though #99 helped to resolve the main container's positioning, it requires navbar to be also in the layout flow to make the main content container shifting right accordingly. The approach fails when navbar is a fixed element.

At this point JS is required. By taking the width of navbar and append that width to the left margin of the main section, main container can be positioned correctly.

**Comment by tim-macphail** [comment]
> > > > I understand the removing of unnecessary styles, but I don't see what is the problem that the changes in `Review.tsx` fixes
> > > 
> > > 
> > > `NavigationDrawer` needs to be `fixed` so that it is **out of** flow layout and container style won't apply to it.
> > > See some css stuff: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flow_Layout/In_Flow_and_Out_of_Flow
> > 
> > 
> > I see that it makes logical sense to have the nav drawer out of flow, and maybe it takes a couple more lines of CSS to override the container styles. But I have a hard time changing something that's simple and works to something that's complicated and I don't know if it works. However, if you still want to follow through with this change I will go along with it, after extensive testing.
> 
> Thought I should probably follow up with some justifications.
> 
> Currently in main branch, the navbar is not fixed and as a part of the layout, it scrolls along with other content.
> 
> However by the definition of a navbar, it shouldn't move as scrolling content. Here's an example of Youtube navbar:
> 
> 
> Making navbar **`fixed`** is making not only logical sense but also **visual sense**. And making an element `fixed` is the only way to make element floating above or below other contents, relative to the whole window (which is different from what `absolute` provides: relative to a `relative` parent element).
> 
> Then making an element `fixed` is taking the element out of the layout flow, which is fairly explained in [that link](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flow_Layout/In_Flow_and_Out_of_Flow).
> 
> The following two code snippets have no difference in effect:
> 
> ```
> <body>
>    <div class="parent">
>      <div class="parent2">
>       <div class="fixed"></div>
>      </div>
>    </div>
> </body>
> ```
> 
> ```
> <body>
>    <div class="parent">
>      <div class="parent2">
>      </div>
>    </div>
>    <div class="fixed"></div>
> </body>
> ```
> 
> Regardless of where you put fixed elements, everything in the layout flow won't observe them or effect them in styles by any means.
> 
> So even though #99 helped to resolve the main container's positioning, it requires navbar to be also in the layout flow to make the main content container shifting right accordingly. The approach fails when navbar is a fixed element.
> 
> (I definitely thought #99 is a better solution, I liked and I approved it, but I forgot about the `fixed` part at then)
> 
> At this point JS is required. By taking the width of navbar and append that width to the left margin of the main section, main container can be positioned correctly.

Ok, the not scrolling part makes a lot of sense. I didn't realize that before. I'll see if I can fix the merge conflicts later today

**Comment by tim-macphail** [comment]
Only a couple of minor bugs left:
MORE/LESS text doesn't show up, and this:

https://user-images.githubusercontent.com/70448914/220718483-2b195e0f-d1b7-4efb-a99f-011015a7fb28.mp4

I think it's just a matter of setting dependencies in the useEffect arrays, I will leave the rest up to you @cloudyyoung

**Comment by cloudyyoung** [comment]
Things are fixed now @tim-macphail

**Review by tim-macphail — APPROVED** [review]

**Pull request merged**
