### PR TITLE
Update files endpoint to return text json

### PR DESCRIPTION
**Pull request by harsweet**
Takes in the pdf and parses it to return its in the JSON

PDF:
Screen Shot 2022-12-08 at 7 22 04 PM

The text JSON:
Screen Shot 2022-12-08 at 7 21 40 PM

### CODE REVIEW

**Review by skilledd007 — CHANGES_REQUESTED** [review]
Line 33: 'sendOutlineFile' does not confirm to snake_case.

**Comment by tim-macphail** [comment]
conflicts in server/requirements.txt need to be resolved

**Comment by tim-macphail** [comment]
A package-lock.json file somehow made its way into server on main, would you mind fixing that in this branch?

**Review by tim-macphail — APPROVED** [review]
LGTM

**Review by skilledd007 — APPROVED** [review]

**Pull request merged**
