### PR TITLE
114 navigation drawer minor issues

### LINKED ISSUE #114: Navigation Drawer: Minor issues
1. The width of the drawer on desktop screens is small than expected, the width should be 260px and it's currently 224px.
2. See https://tailwindcss.com/docs/functions-and-directives#screen and use `screen` function for: https://github.com/techstartucalgary/lifeline/blob/c8f61d8f996f5db14ad48d2cebb59f7255db2558/client/src/pages/Review/Review.module.css#L2-L6
3. For all `Buttons`, define `color` attribute instead of hard-coding colors like `bg-tertiary` since this does not take account colors in hover, disabled, active, focused states, etc.  https://github.com/techstartucalgary/lifeline/blob/c8f61d8f996f5db14ad48d2cebb59f7255db2558/client/src/components/NavigationDrawer/NavigationDrawer.tsx#L100-L114
4. The text color is incorrect, refer Prototype for correct color token https://github.com/techstartucalgary/lifeline/blob/c8f61d8f996f5db14ad48d2cebb59f7255db2558/client/src/components/NavigationDrawer/NavigationDrawer.tsx#L70
5. Instead of defining icon as a children of `Button` component, use `icon` attribute (and `Material Symbols` should be used instead of `Material Icons` which is taken care by the component)https://github.com/techstartucalgary/lifeline/blob/c8f61d8f996f5db14ad48d2cebb59f7255db2558/client/src/components/NavigationDrawer/NavigationDrawer.tsx#L106-L108
6. Remove unnecessary styles nesting such as https://github.com/techstartucalgary/lifeline/blob/c8f61d8f996f5db14ad48d2cebb59f7255db2558/client/src/components/NavigationDrawer/NavigationDrawer.tsx#L109
7. For active course tab, style token `bg-primary-container` shall be used instead https://github.com/techstartucalgary/lifeline/blob/c8f61d8f996f5db14ad48d2cebb59f7255db2558/client/src/components/NavigationDrawer/NavigationDrawer.tsx#L75
8. Both "Courses" title and "Add course" button should hide in phone screens:
Screenshot 2023-02-10 at 4 01 57 PM
Screenshot 2023-02-10 at 4 02 07 PM
9. Drawer should take up whole screen height (or replace the background color gray to the same color as drawer so that it visually takes the whole height) Screenshot 2023-02-10 at 4 03 26 PM
10. Divider has padding, visually shorter
Screenshot 2023-02-10 at 4 04 57 PM
Screenshot 2023-02-10 at 4 06 13 PM

Screenshot 2023-02-10 at 4 05 38 PM
11. When the file is uploading, the loading icon should be `ProgressIndicator` component

### PR DESCRIPTION
**Pull request by cloudyyoung**
Close #114.

This PR includes:
- Fix minor issues in #114
- Refactor `NavigationDrawer`
- Create `NavigationRail`, `List` and `NavigationPanel`
- Remove button decoration on webkit core browsers (Safari)
- Appearance adjustment
- Adjust `AppTopBar`, `Button` and `IconButton`

> **Note**: Since the three navigation components are just really different, decomposition makes `NavigationPanel` a long file and with a little bit of repetition, but it effectively decreases the complexity and easier for future changes.

`NavigationPanel` determines which navigation component to display based on: 

Width | Component
-------|--------------
smaller to `sm` | `List` 
`md` to `xl` | `NavigationRail` **(new)** 
`xl` to wider | `NavigationDrawer`

> **Note**: All of the three components in `/component` are **generic** components now. 

Comparison on `width = 781`:

Screenshot 2023-02-24 at 2 15 11 AM
Screenshot 2023-02-24 at 2 15 22 AM

------

I may or may not break changes in #168 in this PR by accident.... ☹️ HELP

### CODE REVIEW

**Comment by tim-macphail** [comment]
The nav drawer on mobile screens is cut off by the app top bar
image

**Comment by tim-macphail** [comment]
The icon (shape) for a course changes depending if you're on small or large/medium screens.

**Comment by tim-macphail** [comment]
Having the narrower nav rail is a great adjustment for medium screens, but I don't like the way it looks, especially next to the app top bar and when scrolling
image
There's no alignment between the top app bar and the the export button. 

In general the spacing between the all the buttons on the rail seems a bit off. Let's keep the export button at the bottom beneath a `<hr/>`, like how it is on large screens.

**Comment by cloudyyoung** [comment]
> The nav drawer on mobile screens is cut off by the app top bar image

I can't seem to re-produce this bug.

**Comment by tim-macphail** [comment]
> > The nav drawer on mobile screens is cut off by the app top bar image
> 
> I can't seem to re-produce this bug.

Recent push fixed it

**Comment by tim-macphail** [comment]
The icon size for 'Add course' and 'Export' changes size with the window height

https://user-images.githubusercontent.com/70448914/221331041-9b8ca346-d1ec-4483-b39f-a6f2e52c5dca.mp4

**Comment by cloudyyoung** [comment]
> > > The nav drawer on mobile screens is cut off by the app top bar image
> > 
> > 
> > I can't seem to re-produce this bug.
> 
> Recent push fixed it

I opened #174 to fix this bug in the future, because I can't seem to find a way of fixing it. 
The bug only happens when the screen size changes from larger screens to mobile screens, which is fairly not often to happen I think, other usages are still fine, so I'm not too worried about fixing this bug in this PR.

**Comment by cloudyyoung** [comment]
> Having the narrower nav rail is a great adjustment for medium screens, but I don't like the way it looks, especially next to the app top bar and when scrolling image There's no alignment between the top app bar and the the export button.
> 
> In general the spacing between the all the buttons on the rail seems a bit off. Let's keep the export button at the bottom beneath a `<hr/>`, like how it is on large screens.

I adjusted the top spacing and I guess it's better now. 
This component is also like officially defined here: https://m3.material.io/components/navigation-rail/specs. Does it look that bad??

And also it's stated bad practice to put the export button (the FAB button) below tabs: https://m3.material.io/components/navigation-rail/guidelines#3bdde9e4-7698-4dfb-9ffb-36285bca6329

**Comment by tim-macphail** [comment]
> 
> I adjusted the top spacing and I guess it's better now. This component is also like officially defined here: https://m3.material.io/components/navigation-rail/specs. Does it look that bad??
> 
> And also it's stated bad practice to put the export button (the FAB button) below tabs: https://m3.material.io/components/navigation-rail/guidelines#3bdde9e4-7698-4dfb-9ffb-36285bca6329

Okay I see, placing it above the courses makes it fixed and not move when new courses are added. It looks a little better with extra space

Now that I'm seeing this guide, it seems like the shapes (triangle, square, ...) are just *placeholders* in the design guide, which makes a lot of sense because I never really understood why square meant PSYC 203 and circle meant CPSC 331.

**Comment by tim-macphail** [comment]
What if we had icons associated with each faculty/course, and matched by keywords like for the assessment icon?
It might look something like this (but with better matching)
Screenshot from 2023-02-26 12-38-22

**Comment by jaza-k** [comment]
> What if we had icons associated with each faculty/course, and matched by keywords like for the assessment icon? It might look something like this (but with better matching) Screenshot from 2023-02-26 12-38-22

I like this idea actually, we might end up reusing some of the same icons for different courses but it adds a nice touch

**Comment by cloudyyoung** [comment]
> What if we had icons associated with each faculty/course, and matched by keywords like for the assessment icon? It might look something like this (but with better matching)

Opened #188. 

@jaza-k Can you review this PR so it can be merged asap?

**Comment by tim-macphail** [comment]
Fix merge conflicts and I can approve

**Review by tim-macphail — APPROVED** [review]
Didn't really look at everything cuz 17 files change and 500+ insertions but we'll hope for the best

**Pull request merged**
