### PR TITLE
Landing page refactoring

### PR DESCRIPTION
**Pull request by cloudyyoung**
https://user-images.githubusercontent.com/20573623/212016794-74765783-0837-413f-a951-f6efe4fbb928.mov

### CODE REVIEW

**Comment by tim-macphail** [comment]
Looks good, how does this relate to @BradleyLi 's #24 ? Should it override?

**Comment by cloudyyoung** [comment]
> Looks good, how does this relate to @BradleyLi 's #24 ? Should it override?

I'd like it to be overridden by this PR.

This is what it was like:

https://user-images.githubusercontent.com/20573623/212200818-ec714842-47ad-478e-849b-03544000ce4b.mov

**Comment by tim-macphail** [comment]
> > 
> 
> I'd like it to be overridden by this PR.

Ok that works with me

**Comment by tim-macphail** [comment]
Would you mind deleting the package-lock from /server as part of this pr? Idk how that snuck in there again

**Review by BradleyLi — APPROVED** [review]
I think these files are good to be merged.

**Review by skilledd007 — APPROVED** [review]
Looks good.

**Pull request merged**
