### PR TITLE
FE Refinement (2 / ∞): Improve `AppTopBar`

### LINKED ISSUE #147: Minor issues: Top App Bar
This is just a placeholder issue and I'm working on it. Self-explanatory title too.

### PR DESCRIPTION
**Pull request by cloudyyoung**
This PR closes #147. Please merge #149 before this one.

This PR improves (and implements) the `AppTopBar` component according [M3 Guidelines](https://m3.material.io/components/top-app-bar/guidelines) for it.

Including:
- Extended headline section
- [Elevation background upon scrolling scrolling](https://m3.material.io/components/top-app-bar/guidelines#4eab4f50-4a3e-4189-bce2-a46514cde1da)
- [Compress into compact top bar upon scrolling](https://m3.material.io/components/top-app-bar/guidelines#0e9878bc-c1e1-46a5-afa5-4b43a1949dc1)
- Refactorings

> **Note** `AppTopBar` is generalized, so that it can be used for _any_ purpose and page, because "Edit assessment" panel on mobile view is using this component as well (with minor modifications upon this PR).

https://user-images.githubusercontent.com/20573623/220041083-0cdd07cf-b380-482d-9afa-9dc455db458e.mov

### CODE REVIEW

**Comment by cloudyyoung** [comment]
I'm also having difficulty resolving conflict in `Review.tsx` with #155.

I'll eventually have to discard all changes in `AppTopBar` in #155 and only keep changes in this PR so #149 can close. @tim-macphail

**Comment by tim-macphail** [comment]
> I'm also having difficulty resolving conflicts in `Review.tsx` with #155.
> 
> I'll eventually have to discard all changes in `AppTopBar` in #155 and only keep changes in this PR so #147 can close. @tim-macphail

The app top bar looks really good. If it **must** require #149 then we should go through with 149. In the future, please let me know via discord what you'll be working on so I can properly manage this project.

**Review by BradleyLi — APPROVED** [review]
Looks good to me!

**Comment by cloudyyoung** [comment]
> > I'm also having difficulty resolving conflicts in `Review.tsx` with #155.
> > I'll eventually have to discard all changes in `AppTopBar` in #155 and only keep changes in this PR so #147 can close. @tim-macphail
> 
> The app top bar looks really good. If it **must** require #149 then we should go through with 149. In the future, please let me know via discord what you'll be working on so I can properly manage this project.

wdym, I opened #147 right after I merged #139 and said 
> I'm working on it


🥹🥹🥹🥹🥹


It's fine I'll deliver the message to more different places next time...

**Comment by tim-macphail** [comment]
> > > I'm also having difficulty resolving conflicts in `Review.tsx` with #155.
> > > I'll eventually have to discard all changes in `AppTopBar` in #155 and only keep changes in this PR so #147 can close. @tim-macphail
> > 
> > 
> > The app top bar looks really good. If it **must** require #149 then we should go through with 149. In the future, please let me know via discord what you'll be working on so I can properly manage this project.
> 
> wdym, I opened #147 right after I merged #139 and said
> 
> > I'm working on it
> 
> 🥹🥹🥹🥹🥹
> 
> It's fine I'll deliver the message to more different places next time...

Thanks. Yeah this is pretty much all my fault, but I did ask you to lmk what you're going to be doing on discord so let's just keep communication on both. It's just harder to find all messages on gh. In the future I'll be sure to not work on anything you're assigned to. I fixed merge conflicts on `148-minor-issues-dom-structure` but I'm waiting for your permission to push them, so we can leave this in the past soon

**Pull request merged**
