### PR TITLE
Course failure handling and frontend optimization

### PR DESCRIPTION
**Pull request by cloudyyoung**
This PR is branched off from #117 and fixes issues in that PR, so please merge #117 before this one.
This PR also includes several refactorings.

### Changes
- Move _response data_ processing logic from `NavigationDrawer` to `Review` for low-coupling
- Refactor `courseKey` in url params and relative page switching
- Extending `Courses` interface from `Array<Course>` (equivalent to `Course[]`, an array of `Course` objects), since `Review` seems to be the only place that needs to have a "lookup table" in the format of `{ [courseKey]: Course }` for quick access, `NavigationDrawer` and `icsGen` works perfectly well with an array, so components (and between FE and BE) are passing an __array__ of `Course` now
- Introduce `courseKeyLookup: Record<string, Course>` dictionary for quick access in `Review`, with `useMemo` it is cached and re-calculate whenever `courses` changes
- Introduce `currentCourse: Course` as the current selected course for performance, with `useMemo` it is cached and re-calculate whever `currentCourseKey` or content in `courseKeyLookup[currentCourseKey]` changes

### Future notes
`Review` is getting longer and longer and that makes sense as it contains all the hook-up logics, and to not burying hook-up logics deep down in relative sub-components. When it gets too long, we could move callback functions to a file such as `hooks.ts` and have ReactNodes in a separate file such as `ReviewView.tsx`.

For-loops requires a `key` to all children. Make life easier to not come up with unique keys, here's a trick:
```js
array.map((element, index) => (<Component key={index} />));
```

### CODE REVIEW

**Comment by tim-macphail** [comment]
Refactoring looks good. I noticed there's a delay when switching between tabs that didn't used to be there... not sure when that was introduced. Could it be the new useEffect? 

Also if you multiple upload files that are not determinable like PSYC 203 and ARHI 201 in different batches, each time they're called `Course 1` which is not the expected behavior. Also leads to duplicate key prop errors in the console.
Screenshot from 2023-02-10 23-43-55

**Comment by cloudyyoung** [comment]
> Refactoring looks good. I noticed there's a delay when switching between tabs that didn't used to be there... not sure when that was introduced. Could it be the new useEffect?
> 
> Also if you multiple upload files that are not determinable like PSYC 203 and ARHI 201 in different batches, each time they're called `Course 1` which is not the expected behavior. Also leads to duplicate key prop errors in the console. Screenshot from 2023-02-10 23-43-55

Good catch! I've moved the numbering logic to frontend.

Investigating the performance issue...

**Comment by cloudyyoung** [comment]
Performance issue is optimized in https://github.com/techstartucalgary/lifeline/pull/118/commits/42b4ca772c2123d6122e4e9862989530fd7af07a

**Comment by tim-macphail** [comment]
I'm still noticing really poor performance switching to tabs with a lot of assessments (try PSYC 203.pdf). I don't think we need to solve it in this PR. Maybe we could use some react hooks to make the UI feel smother if we can't make it fast.

**Review by tim-macphail — APPROVED** [review]
Go for it

**Review by tim-macphail — CHANGES_REQUESTED** [review]
Wait, there's a bug with uploading the same file twice.
Screenshot from 2023-02-11 17-38-51

**Comment by cloudyyoung** [comment]
I'm really confused now... 

If you select the same file twice it's not doing anything. And the tab switching is smooth enough from what I see, and it wasn't even that bad before the fix either, like the fix improved about 0.5 seconds. Are we on the same project im so confused lol, let me show you a video


https://user-images.githubusercontent.com/20573623/218287199-64639272-0f29-47de-a0b7-e0e04f70e977.mov

**Comment by tim-macphail** [comment]
> I'm really confused now...
> 
> If you select the same file twice it's not doing anything. And the tab switching is smooth enough from what I see, and it wasn't even that bad before the fix neither, like the fix improved about 0.5 seconds. Are we on the same project im so confused lol, let me show you a video
> Screen.Recording.2023-02-11.at.5.44.52.PM.1.1.mov

The tab switching slowness has been in nav drawer, the assessments/documents tab has always been fine. I'm 100% up to date with `yunfan/get-course-failure-handling` and I still get the duplicate tab highlighted bug... on Firefox 109.0.1 on Ubuntu

**Comment by tim-macphail** [comment]
[Screencast from 2023-02-11 08:44:49 PM.webm](https://user-images.githubusercontent.com/70448914/218291902-ec3173e6-3e75-411e-8796-877921b7a721.webm)

[Screencast from 2023-02-11 08:46:48 PM.webm](https://user-images.githubusercontent.com/70448914/218291937-39d15d8b-6fa5-4a18-b7e8-b0b8aaebd2e8.webm)

**Comment by cloudyyoung** [comment]
I suspect that's a browser behaviour issue. Anyways, it's preventing duplicate course to be displayed now.

**Comment by tim-macphail** [comment]
> I suspect that's a browser behaviour issue. Anyways, it's preventing duplicate course to be displayed now.

That worked for the duplicate courses. You can see the lag in selecting a tab with 38 assessments though, it's pretty bad and I don't think it should be. The quantity of data we're processing and the asymptotic complexity of the operations should be pretty trivial even for a 5 year old laptop with 8 G ram

**Review by tim-macphail — APPROVED** [review]

**Comment by cloudyyoung** [comment]
I didn't observe lag for course with single digit number of assessments but did observe when there are many like 39 assessments. Apparently more time were spent rendering the list when there are more assessments. https://blog.logrocket.com/options-caching-react/

**Comment by tim-macphail** [comment]
A rendering animation could help with this

**Pull request merged**
